# syntax=docker/dockerfile:1.2
# 1.2: RUN --mount

FROM spcleth/xaas:llvm-19

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked --mount=type=cache,target=/var/lib/apt,sharing=locked --mount=type=tmpfs,target=/var/log/apt \
    eatmydata apt-get update && eatmydata apt-get install -y \
    libclang-19-dev \
    libzstd-dev

RUN mkdir /tools
ADD tools/ /tools/openmp-finder
RUN cd /tools/openmp-finder && cmake -DCMAKE_BUILD_TYPE=Release . && make -j$( nproc )
