FROM spcleth/xaas:llvm as builder

WORKDIR /tmp

USER root

RUN wget https://www.mpich.org/static/downloads/4.3.0/mpich-4.3.0.tar.gz \
    && tar -xf mpich-4.3.0.tar.gz \
    && cd mpich-4.3.0 \
    && ./configure --prefix=/opt/mpich \
    && make -j8 && make install

FROM ubuntu:22.04

COPY --from=builder /opt/mpich /opt/mpich
