FROM spcleth/xaas:llvm-19-dev

RUN apt-get update && apt-get install libclang-19-dev zstd libzstd-dev

#RUN mkdir /tools && chown docker_user:docker_user /tools
RUN mkdir /tools  && mkdir /tools/build
ADD tools/llvm-features /tools/feature-analyzer
RUN  cd /tools/build && LLVM_DIR=/opt/llvm/ cmake -DLLVM_DIR="/opt/llvm/" -DCMAKE_BUILD_TYPE=Release /tools/feature-analyzer && make 
