# syntax=docker/dockerfile:1.4
# 1.4: COPY --link

FROM spcleth/xaas:llvm-19 as builder

WORKDIR /tmp

USER root

RUN wget https://www.mpich.org/static/downloads/4.3.0/mpich-4.3.0.tar.gz \
    && tar -xf mpich-4.3.0.tar.gz \
    && cd mpich-4.3.0 \
    && ./configure --prefix=/opt/mpich \
    && make -j8 && make install \
    && cd .. && rm -r mpich-4.3.0

FROM scratch

COPY --link --from=builder /opt/mpich /opt/mpich
