FROM spcleth/xaas:llvm-19

#USER root

RUN apt-get update && apt-get install libclang-19-dev zstd libzstd-dev

#RUN mkdir /tools && chown docker_user:docker_user /tools
RUN mkdir /tools 
ADD tools/llvm-features /tools/feature-analyzer
RUN cd /tools/feature-analyzer && cmake -DCMAKE_BUILD_TYPE=Release . && make 
