working_directory: lulesh-builds
source_directory: LULESH
project_name: LULESH
build_system: cmake
features_select: {}
features_boolean:
  MPI: [WITH_MPI=ON, WITH_MPI=OFF]
  OPENMP: [WITH_OPENMP=ON, WITH_OPENMP=OFF]
additional_args: []
additional_steps: []
