working_directory: lulesh-builds
source_directory: LULESH
project_name: LULESH
build_system: cmake
cpu_architecture: x86_64
features_select: {}
features_boolean:
  MPI:
    enabled:
      property_set:
        WITH_MPI: ['ON']
    disabled:
      property_set:
        WITH_MPI: ['OFF']
  OPENMP:
    enabled:
      property_set:
        WITH_OPENMP: ['ON']
    disabled:
      property_set:
        WITH_OPENMP: ['OFF']
build_args: {}
additional_steps: []
