layers:
  x86_64:
    mpich:
      versions: ['4.3.0']
      version_arg: MPICH_VERSION
      builder_paths:
        - image_tag: docker.io/spcleth/xaas:${XAAS_SYSTEM_VERSION}-layer-mpich${MPICH_VERSION}
          src_path: /opt/mpich
          dst_path: /opt/mpich
      builder_env:
        MPI_HOME: '/opt/mpich'
      runtime_paths:
        - image_tag: docker.io/spcleth/xaas:${XAAS_SYSTEM_VERSION}-layer-mpich${MPICH_VERSION}
          src_path: /opt/mpich
          dst_path: /opt/mpich
    cuda:
      versions: ['13.1', '13.3']
      version_arg: CUDA_VERSION
      all_paths:
        - image_tag: docker.io/spcleth/xaas:${XAAS_SYSTEM_VERSION}-layer-cuda${CUDA_VERSION}
          src_path: /usr/local/cuda-${CUDA_VERSION}
          dst_path: /usr/local/cuda-${CUDA_VERSION}
      all_env:
        PATH:
          type: append
          value: /usr/local/cuda-${CUDA_VERSION}/bin
          separator: ':'
        LD_LIBRARY_PATH:
          type: append
          value: /usr/local/cuda-${CUDA_VERSION}/lib64
          separator: ':'
    fftw3:
      versions: ['3.3.10']
      version_arg: FFTW3_VERSION
      all_paths:
        - image_tag: docker.io/spcleth/xaas:${XAAS_SYSTEM_VERSION}-layer-fftw${FFTW3_VERSION}-${SIMD_FLAG}
          src_path: /opt/fftw3
          dst_path: /opt/fftw3
      all_env:
        PKG_CONFIG_PATH:
          type: append
          value: /opt/fftw3/lib/pkgconfig
          separator: ':'

      arg_mapping:
        VECTORIZATION:
          flag_name: SIMD_FLAG
    oneapi:
      versions: ['2021.3.0', '2025.0']
      version_arg: ONEAPI_VERSION
      all_paths:
        - image_tag: docker.io/spcleth/xaas:${XAAS_SYSTEM_VERSION}-layer-oneapi${ONEAPI_VERSION}
          src_path: /opt/intel
          dst_path: /opt/intel
      arg_mapping:
        ONEAPI_VERSION:
          flag_name: ONEAPI_VERSION
  arm64:
    cuda:
      versions: ['12.6']
      version_arg: CUDA_VERSION
      all_paths:
        - image_tag: docker.io/spcleth/xaas:${XAAS_SYSTEM_VERSION}-cuda-${CUDA_VERSION}-arm
          src_path: /usr/local/cuda-${CUDA_VERSION}
          dst_path: /usr/local/cuda-${CUDA_VERSION}
      all_env:
        PATH:
          type: append
          value: /usr/local/cuda-${CUDA_VERSION}/bin
          separator: ':'
        LD_LIBRARY_PATH:
          type: append
          value: /usr/local/cuda-${CUDA_VERSION}/lib64
          separator: ':'
