layers:
  x86_64:
    MPI:
      dockerfile: Dockerfile.mpich
      versions: [4.3.0]
      name: mpich
      version_arg: MPICH_VERSION
      build_location: /opt/mpich
      runtime_location: /opt/mpich
    CUDA:
      dockerfile: Dockerfile.cuda
      name: cuda-${CUDA_VERSION}
      versions: [12.1, 12.8]
      version_arg: CUDA_VERSION
      build_location: /usr/local/cuda-${CUDA_VERSION}
      runtime_location: /usr/local/cuda-${CUDA_VERSION}
      envs:
        PATH: /usr/local/cuda-${CUDA_VERSION}/bin
        LD_LIBRARY_PATH: /usr/local/cuda-${CUDA_VERSION}/lib64
    ONEAPI:
      dockerfile: Dockerfile.oneapi
      name: oneapi-${ONEAPI_VERSION}
      versions: [2021.3.0, 2025.0]
      version_arg: ONEAPI_VERSION
      build_location: /opt/intel
      runtime_location: /opt/intel
      arg_mapping:
        ONEAPI_VERSION:
          flag_name: ONEAPI_VERSION
          build_args:
            2021.3.0: intel-basekit-2021.3.0
            2025.0: intel-oneapi-base-toolkit-2025.0
  arm64:
    CUDA:
      dockerfile: Dockerfile.cuda-arm
      name: cuda-${CUDA_VERSION}-arm
      versions: [12.6]
      version_arg: CUDA_VERSION
      build_location: /usr/local/cuda-${CUDA_VERSION}
      runtime_location: /usr/local/cuda-${CUDA_VERSION}
      envs:
        PATH: /usr/local/cuda-${CUDA_VERSION}/bin
        LD_LIBRARY_PATH: /usr/local/cuda-${CUDA_VERSION}/lib64
layers_deps:
  x86_64:
    fftw3:
      dockerfile: deps/Dockerfile.fftw
      name: deps-fftw3-${version}-${SIMD_FLAG}
      versions: [3.3.10]
      version_arg: FFTW3_VERSION
      arg_mapping:
        VECTORIZATION:
          flag_name: SIMD_FLAG
          build_args:
            SSE2: --enable-sse2
            SSE4.1: --enable-sse2
            AVX_256: --enable-sse2 --enable-avx --enable-avx2
            AVX2_128: --enable-sse2 --enable-avx --enable-avx2
            AVX2_256: --enable-sse2 --enable-avx --enable-avx2
            AVX_512: --enable-sse2 --enable-avx --enable-avx2 --enable-avx512

      build_location: /opt/fftw3
      runtime_location: /opt/fftw3
      envs:
        PKG_CONFIG_PATH: /opt/fftw3/lib/pkgconfig
