config_vars:
  XAAS_SYSTEM_REPO: "docker.io/spcleth/xaas"
  XAAS_SYSTEM_VERSION: "1_rc1"

  DEBIAN_VERSION: "13"
  LLVM_VERSION: "19"

default_builder_image: "${XAAS_SYSTEM_REPO}:${XAAS_SYSTEM_VERSION}-builder-debian${DEBIAN_VERSION}-llvm${LLVM_VERSION}"
default_runtime_image: "${XAAS_SYSTEM_REPO}:${XAAS_SYSTEM_VERSION}-runner-debian${DEBIAN_VERSION}-llvm${LLVM_VERSION}"

ir_type: "llvm-ir"
parallelism_level: 4
